// Every Malapos feature route, one method each — generated by apigen from
// backend/openapi.json. Do not edit by hand; regenerate after the API changes.
// Reach them as `client.api.<area><Action>(...)`; each call goes through the client's
// own `apigenRequest` (its sign-in and response envelope).

export interface ApigenTransport {
  apigenRequest(method: string, path: string, query: Record<string, unknown> | undefined, body: unknown): Promise<unknown>;
}

/** All 240 feature routes of the Malapos API. */
export class GeneratedApi {
  constructor(private readonly client: ApigenTransport) {}

  private call(method: string, path: string, query: Record<string, unknown>, body: unknown): Promise<unknown> {
    const q = Object.fromEntries(Object.entries(query).filter(([, v]) => v !== undefined && v !== null));
    return this.client.apigenRequest(method, path, Object.keys(q).length ? q : undefined, body);
  }

  /** List abandoned cart (GET /api/v1/account/abandoned-cart) */
  accountAbandonedCart(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/abandoned-cart`, {}, undefined);
  }

  /** List reminders (GET /api/v1/account/abandoned-cart/reminders) */
  accountAbandonedCartReminders(input?: { "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/account/abandoned-cart/reminders`, query, undefined);
  }

  /** List stats (GET /api/v1/account/abandoned-cart/stats) */
  accountAbandonedCartStats(input?: { "windowDays"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["windowDays"] = all["windowDays"]; delete all["windowDays"];
    return this.call("GET", `/api/v1/account/abandoned-cart/stats`, query, undefined);
  }

  /** List posts (GET /api/v1/account/blog/posts) */
  accountBlogPosts(input?: { "status"?: "draft" | "published"; "limit"?: number; "cursor"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["status"] = all["status"]; delete all["status"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    return this.call("GET", `/api/v1/account/blog/posts`, query, undefined);
  }

  /** Publish a post (POST /api/v1/account/blog/posts/{id}/publish) */
  accountBlogPostsPublish(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/account/blog/posts/${encodeURIComponent(id)}/publish`, {}, undefined);
  }

  /** Unpublish a post (POST /api/v1/account/blog/posts/{id}/unpublish) */
  accountBlogPostsUnpublish(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/account/blog/posts/${encodeURIComponent(id)}/unpublish`, {}, undefined);
  }

  /** Create a post (POST /api/v1/account/blog/posts) */
  accountCreateBlogPosts(input: { "title": string; "slug"?: string; "excerpt"?: string; "body": string; "coverImage"?: string; "status"?: "draft" | "published"; "publishedAt"?: string; "authorName"?: string; "tags"?: unknown[]; "metaTitle"?: string; "metaDescription"?: string; "marketingCampaignId"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/account/blog/posts`, query, all);
  }

  /** Delete a post (DELETE /api/v1/account/blog/posts/{id}) */
  accountDeleteBlogPosts(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/account/blog/posts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List feeds (GET /api/v1/account/feeds) */
  accountFeeds(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/feeds`, {}, undefined);
  }

  /** List preview (GET /api/v1/account/feeds/preview) */
  accountFeedsPreview(input?: { "format"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["format"] = all["format"]; delete all["format"];
    return this.call("GET", `/api/v1/account/feeds/preview`, query, undefined);
  }

  /** Get a post (GET /api/v1/account/blog/posts/{id}) */
  accountGetBlogPosts(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/account/blog/posts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Resolve the creator's signed S3 avatar URL via Ripllo's public uploads endpoint, then stream the bytes. (GET /api/v1/account/marketing-media/avatar) */
  accountMarketingMediaAvatar(input?: { "key"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["key"] = all["key"]; delete all["key"];
    return this.call("GET", `/api/v1/account/marketing-media/avatar`, query, undefined);
  }

  /** List pixels (GET /api/v1/account/pixels) */
  accountPixels(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/pixels`, {}, undefined);
  }

  /** List referrals (GET /api/v1/account/referrals) */
  accountReferrals(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/referrals`, {}, undefined);
  }

  /** List attributions (GET /api/v1/account/referrals/attributions) */
  accountReferralsAttributions(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/referrals/attributions`, {}, undefined);
  }

  /** List links (GET /api/v1/account/referrals/links) */
  accountReferralsLinks(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/referrals/links`, {}, undefined);
  }

  /** List stats (GET /api/v1/account/referrals/stats) */
  accountReferralsStats(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/referrals/stats`, {}, undefined);
  }

  /** Set referrals (PUT /api/v1/account/referrals) */
  accountSetReferrals(input: { "enabled"?: boolean; "rewardType": "percent" | "fixed" | "shipping_percent" | "shipping_fixed"; "referrerValue": number; "refereeValue": number; "currency": string; "minPurchaseAmount"?: number; "rewardExpiryDays"?: number; "attributionWindowDays"?: number; "maxRewardsPerReferrer"?: number; "programTerms"?: string; "marketingCampaignId"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/account/referrals`, query, all);
  }

  /** Update abandoned cart (PATCH /api/v1/account/abandoned-cart) */
  accountUpdateAbandonedCart(input?: { "enabled"?: boolean; "delayHours"?: number; "emailSubject"?: string; "emailPreview"?: string; "discountCodeId"?: string; "marketingCampaignId"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/account/abandoned-cart`, query, all);
  }

  /** Update a post (PATCH /api/v1/account/blog/posts/{id}) */
  accountUpdateBlogPosts(id: string, input?: { "title"?: string; "slug"?: string; "excerpt"?: string; "body"?: string; "coverImage"?: string; "status"?: "draft" | "published"; "publishedAt"?: string; "authorName"?: string; "tags"?: unknown[]; "metaTitle"?: string; "metaDescription"?: string; "marketingCampaignId"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/account/blog/posts/${encodeURIComponent(id)}`, query, all);
  }

  /** Update feeds (PATCH /api/v1/account/feeds) */
  accountUpdateFeeds(input?: { "enabled"?: boolean; "defaultGoogleProductCategory"?: string; "includeUnpublished"?: boolean; "marketingCampaignId"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/account/feeds`, query, all);
  }

  /** Update pixels (PATCH /api/v1/account/pixels) */
  accountUpdatePixels(input?: { "metaPixelId"?: string; "metaCapiAccessToken"?: string; "metaTestEventCode"?: string; "googleAnalyticsId"?: string; "googleAdsConversionId"?: string; "googleAdsPurchaseLabel"?: string; "tiktokPixelId"?: string; "enabled"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/account/pixels`, query, all);
  }

  /** Create an api key (POST /api/v1/api-keys) */
  apiKeysCreate(input: { "name": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/api-keys`, query, all);
  }

  /** Delete an api key (DELETE /api/v1/api-keys/{id}) */
  apiKeysDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/api-keys/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List api keys (GET /api/v1/api-keys) */
  apiKeysList(): Promise<unknown> {
    return this.call("GET", `/api/v1/api-keys`, {}, undefined);
  }

  /** List audit log (GET /api/v1/audit-log) */
  auditLogList(input?: { "type"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["type"] = all["type"]; delete all["type"];
    return this.call("GET", `/api/v1/audit-log`, query, undefined);
  }

  /** Downgrade to Free. (POST /api/v1/billing/cancel) */
  billingCancel(): Promise<unknown> {
    return this.call("POST", `/api/v1/billing/cancel`, {}, undefined);
  }

  /** POST /checkout {tier, currency?} — create a Plugipay hosted checkout session for a paid tier; the browser redirects to data.hostedUrl. `currency` is the buyer's saved preference (the billing page pass (POST /api/v1/billing/checkout) */
  billingCheckout(input: { "tier": "free" | "starter" | "growth" | "business"; "currency"?: "IDR" | "USD"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/billing/checkout`, query, all);
  }

  /** Current subscription (free default when no row) + effectiveTier (what enforcement honors: lapsed/canceled fall back to free) + the tier table. (GET /api/v1/billing) */
  billingList(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing`, {}, undefined);
  }

  /** Public plan catalog. (GET /api/v1/billing/tiers) */
  billingTiers(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/tiers`, {}, undefined);
  }

  /** Create a category (POST /api/v1/categories) */
  categoriesCreate(input: { "name": string; "sortOrder"?: number; "isActive"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/categories`, query, all);
  }

  /** Delete a category (DELETE /api/v1/categories/{id}) */
  categoriesDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/categories/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List categories (GET /api/v1/categories) */
  categoriesList(): Promise<unknown> {
    return this.call("GET", `/api/v1/categories`, {}, undefined);
  }

  /** Create a reorder (POST /api/v1/categories/reorder) */
  categoriesReorder(input: { "ids": unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/categories/reorder`, query, all);
  }

  /** Update a category (PATCH /api/v1/categories/{id}) */
  categoriesUpdate(id: string, input?: { "name"?: string; "sortOrder"?: number; "isActive"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/categories/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a customer (POST /api/v1/customers) */
  customersCreate(input: { "name": string; "phone"?: string; "email"?: string; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/customers`, query, all);
  }

  /** Delete a customer (DELETE /api/v1/customers/{id}) */
  customersDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/customers/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a customer (GET /api/v1/customers/{id}) */
  customersGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/customers/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List customers (GET /api/v1/customers) */
  customersList(input?: { "q"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["q"] = all["q"]; delete all["q"];
    return this.call("GET", `/api/v1/customers`, query, undefined);
  }

  /** List loyalty (GET /api/v1/customers/{id}/loyalty) */
  customersLoyalty(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/customers/${encodeURIComponent(id)}/loyalty`, {}, undefined);
  }

  /** Create an adjust (POST /api/v1/customers/{id}/loyalty/adjust) */
  customersLoyaltyAdjust(id: string, input: { "points": number; "reason"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/customers/${encodeURIComponent(id)}/loyalty/adjust`, query, all);
  }

  /** Create a redeem (POST /api/v1/customers/{id}/loyalty/redeem) */
  customersLoyaltyRedeem(id: string, input: { "points": number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/customers/${encodeURIComponent(id)}/loyalty/redeem`, query, all);
  }

  /** Update a customer (PATCH /api/v1/customers/{id}) */
  customersUpdate(id: string, input?: { "name"?: string; "phone"?: string; "email"?: string; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/customers/${encodeURIComponent(id)}`, query, all);
  }

  /** List couriers (GET /api/v1/delivery/couriers) */
  deliveryCouriers(): Promise<unknown> {
    return this.call("GET", `/api/v1/delivery/couriers`, {}, undefined);
  }

  /** Create a delivery shipment for a sale. (POST /api/v1/delivery/shipments) */
  deliveryCreateShipments(input?: { "courierCode"?: unknown; "courierServiceCode"?: unknown; "courierType"?: unknown; "customerEmail"?: unknown; "customerId"?: unknown; "destination"?: unknown; "insurance"?: unknown; "insured"?: unknown; "items"?: unknown; "price"?: unknown; "transactionId"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/delivery/shipments`, query, all);
  }

  /** Get a shipment (GET /api/v1/delivery/shipments/{id}) */
  deliveryGetShipments(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/delivery/shipments/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List origin (GET /api/v1/delivery/origin) */
  deliveryOrigin(): Promise<unknown> {
    return this.call("GET", `/api/v1/delivery/origin`, {}, undefined);
  }

  /** Create a rate (POST /api/v1/delivery/rates) */
  deliveryRates(input?: { "destination"?: unknown; "insurance"?: unknown; "items"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/delivery/rates`, query, all);
  }

  /** Deferred dispatch. (POST /api/v1/delivery/sales/{id}/dispatch) */
  deliverySalesDispatch(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/delivery/sales/${encodeURIComponent(id)}/dispatch`, {}, undefined);
  }

  /** List shipments (GET /api/v1/delivery/shipments) */
  deliveryShipments(input?: { "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/delivery/shipments`, query, undefined);
  }

  /** Cancel a shipment (POST /api/v1/delivery/shipments/{id}/cancel) */
  deliveryShipmentsCancel(id: string, input?: { "reason"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/delivery/shipments/${encodeURIComponent(id)}/cancel`, query, all);
  }

  /** F-004 equivalent — "Book courier": flip the draft into a real Biteship order once the parcel is packed. (POST /api/v1/delivery/shipments/{id}/confirm-pickup) */
  deliveryShipmentsConfirmPickup(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/delivery/shipments/${encodeURIComponent(id)}/confirm-pickup`, {}, undefined);
  }

  /** Update origin (PATCH /api/v1/delivery/origin) */
  deliveryUpdateOrigin(input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/delivery/origin`, query, all);
  }

  /** List stream (GET /api/v1/events/stream) */
  eventsStream(input?: { "outletId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("GET", `/api/v1/events/stream`, query, undefined);
  }

  /** Create a floor (POST /api/v1/floors) */
  floorsCreate(input: { "outletId": string; "name": string; "sortOrder"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/floors`, query, all);
  }

  /** Remove a floor. (DELETE /api/v1/floors/{id}) */
  floorsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/floors/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List floors (GET /api/v1/floors) */
  floorsList(input: { "outletId": unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("GET", `/api/v1/floors`, query, undefined);
  }

  /** Update a floor (PATCH /api/v1/floors/{id}) */
  floorsUpdate(id: string, input?: { "name"?: string; "sortOrder"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/floors/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a license (POST /api/v1/fulfillment/licenses) */
  fulfillmentCreateLicenses(input: { "productId": string; "customerId": string; "maxActivations"?: number; "expiresAt"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/fulfillment/licenses`, query, all);
  }

  /** Create a shipment (POST /api/v1/fulfillment/shipments) */
  fulfillmentCreateShipments(input: { "transactionId"?: string; "customerId"?: string; "customerEmail"?: string; "courierCode": string; "courierServiceCode": string; "courierType"?: string; "price"?: number; "insured"?: boolean; "insurance"?: number; "destination": Record<string, unknown>; "items": unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/fulfillment/shipments`, query, all);
  }

  /** Create a warehouse (POST /api/v1/fulfillment/warehouses) */
  fulfillmentCreateWarehouses(input: { "name": string; "address"?: string; "city"?: string; "postal"?: string; "phone"?: string; "isDefault"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/fulfillment/warehouses`, query, all);
  }

  /** Delete a warehouse (DELETE /api/v1/fulfillment/warehouses/{id}) */
  fulfillmentDeleteWarehouses(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/fulfillment/warehouses/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List deliveries (GET /api/v1/fulfillment/deliveries) */
  fulfillmentDeliveries(): Promise<unknown> {
    return this.call("GET", `/api/v1/fulfillment/deliveries`, {}, undefined);
  }

  /** Get a delivery (GET /api/v1/fulfillment/deliveries/{id}) */
  fulfillmentGetDeliveries(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/fulfillment/deliveries/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a shipment (GET /api/v1/fulfillment/shipments/{id}) */
  fulfillmentGetShipments(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/fulfillment/shipments/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Create an adjust (POST /api/v1/fulfillment/inventory/adjust) */
  fulfillmentInventoryAdjust(input: { "variantId": string; "warehouseId": string; "delta": number; "reason": "manual_adjust" | "refund_restock" | "transfer_in" | "transfer_out" | "damaged" | "returned_to_supplier" | "initial_stock" | "import"; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/fulfillment/inventory/adjust`, query, all);
  }

  /** List movements (GET /api/v1/fulfillment/inventory/movements) */
  fulfillmentInventoryMovements(input?: { "variantId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["variantId"] = all["variantId"]; delete all["variantId"];
    return this.call("GET", `/api/v1/fulfillment/inventory/movements`, query, undefined);
  }

  /** Fulkruma-side products (with their variants) — the inventory grid lists a row per variant/warehouse pair from these. (GET /api/v1/fulfillment/inventory/products) */
  fulfillmentInventoryProducts(): Promise<unknown> {
    return this.call("GET", `/api/v1/fulfillment/inventory/products`, {}, undefined);
  }

  /** List stock (GET /api/v1/fulfillment/inventory/stock) */
  fulfillmentInventoryStock(input?: { "variantId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["variantId"] = all["variantId"]; delete all["variantId"];
    return this.call("GET", `/api/v1/fulfillment/inventory/stock`, query, undefined);
  }

  /** List licenses (GET /api/v1/fulfillment/licenses) */
  fulfillmentLicenses(): Promise<unknown> {
    return this.call("GET", `/api/v1/fulfillment/licenses`, {}, undefined);
  }

  /** Revoke a license (POST /api/v1/fulfillment/licenses/{id}/revoke) */
  fulfillmentLicensesRevoke(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/fulfillment/licenses/${encodeURIComponent(id)}/revoke`, {}, undefined);
  }

  /** List validate (GET /api/v1/fulfillment/licenses/validate) */
  fulfillmentLicensesValidate(input: { "key": unknown; "productId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["key"] = all["key"]; delete all["key"];
    query["productId"] = all["productId"]; delete all["productId"];
    return this.call("GET", `/api/v1/fulfillment/licenses/validate`, query, undefined);
  }

  /** List shipments (GET /api/v1/fulfillment/shipments) */
  fulfillmentShipments(input?: { "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/fulfillment/shipments`, query, undefined);
  }

  /** Cancel a booking the courier hasn't collected. (POST /api/v1/fulfillment/shipments/{id}/cancel) */
  fulfillmentShipmentsCancel(id: string, input?: { "reason"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/fulfillment/shipments/${encodeURIComponent(id)}/cancel`, query, all);
  }

  /** Confirm pickup a shipment (POST /api/v1/fulfillment/shipments/{id}/confirm-pickup) */
  fulfillmentShipmentsConfirmPickup(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/fulfillment/shipments/${encodeURIComponent(id)}/confirm-pickup`, {}, undefined);
  }

  /** List label (GET /api/v1/fulfillment/shipments/{id}/label) */
  fulfillmentShipmentsLabel(id: string, input?: { "size"?: "a4" | "thermal-80x100" | "thermal-100x150"; "showSenderPhone"?: "true" | "false"; "showRecipientPhone"?: "true" | "false"; "maskRecipientName"?: "true" | "false"; "showShippingCost"?: "true" | "false"; "showInsurance"?: "true" | "false"; "showItems"?: "true" | "false"; "showItemDescriptions"?: "true" | "false"; "showItemSkus"?: "true" | "false" }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["size"] = all["size"]; delete all["size"];
    query["showSenderPhone"] = all["showSenderPhone"]; delete all["showSenderPhone"];
    query["showRecipientPhone"] = all["showRecipientPhone"]; delete all["showRecipientPhone"];
    query["maskRecipientName"] = all["maskRecipientName"]; delete all["maskRecipientName"];
    query["showShippingCost"] = all["showShippingCost"]; delete all["showShippingCost"];
    query["showInsurance"] = all["showInsurance"]; delete all["showInsurance"];
    query["showItems"] = all["showItems"]; delete all["showItems"];
    query["showItemDescriptions"] = all["showItemDescriptions"]; delete all["showItemDescriptions"];
    query["showItemSkus"] = all["showItemSkus"]; delete all["showItemSkus"];
    return this.call("GET", `/api/v1/fulfillment/shipments/${encodeURIComponent(id)}/label`, query, undefined);
  }

  /** Rebook a shipment (POST /api/v1/fulfillment/shipments/{id}/rebook) */
  fulfillmentShipmentsRebook(id: string, input?: { "courierCode"?: string; "courierServiceCode"?: string; "courierType"?: string; "price"?: number; "insured"?: boolean; "insurance"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/fulfillment/shipments/${encodeURIComponent(id)}/rebook`, query, all);
  }

  /** List couriers (GET /api/v1/fulfillment/shipping/couriers) */
  fulfillmentShippingCouriers(): Promise<unknown> {
    return this.call("GET", `/api/v1/fulfillment/shipping/couriers`, {}, undefined);
  }

  /** List origin (GET /api/v1/fulfillment/shipping/origin) */
  fulfillmentShippingOrigin(): Promise<unknown> {
    return this.call("GET", `/api/v1/fulfillment/shipping/origin`, {}, undefined);
  }

  /** Create a rate (POST /api/v1/fulfillment/shipping/rates) */
  fulfillmentShippingRates(input?: { "destination"?: unknown; "insurance"?: unknown; "items"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/fulfillment/shipping/rates`, query, all);
  }

  /** Public buyer tracking lives on fulkruma.com — keep the route present so the chrome never 404s, but redirect callers to the canonical tracker. (GET /api/v1/fulfillment/shipping/track/{waybillId}) */
  fulfillmentShippingTrack(waybillId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/fulfillment/shipping/track/${encodeURIComponent(waybillId)}`, {}, undefined);
  }

  /** List shipping credits (GET /api/v1/fulfillment/shipping-credits) */
  fulfillmentShippingCredits(): Promise<unknown> {
    return this.call("GET", `/api/v1/fulfillment/shipping-credits`, {}, undefined);
  }

  /** Create a topup (POST /api/v1/fulfillment/shipping-credits/topup) */
  fulfillmentShippingCreditsTopup(input: { "amount": number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/fulfillment/shipping-credits/topup`, query, all);
  }

  /** List transactions (GET /api/v1/fulfillment/shipping-credits/transactions) */
  fulfillmentShippingCreditsTransactions(input?: { "cursor"?: unknown; "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/fulfillment/shipping-credits/transactions`, query, undefined);
  }

  /** Update origin (PATCH /api/v1/fulfillment/shipping/origin) */
  fulfillmentUpdateShippingOrigin(input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/fulfillment/shipping/origin`, query, all);
  }

  /** Update a warehouse (PATCH /api/v1/fulfillment/warehouses/{id}) */
  fulfillmentUpdateWarehouses(id: string, input?: { "name"?: string; "address"?: string; "city"?: string; "postal"?: string; "phone"?: string; "isDefault"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/fulfillment/warehouses/${encodeURIComponent(id)}`, query, all);
  }

  /** List warehouses (GET /api/v1/fulfillment/warehouses) */
  fulfillmentWarehouses(): Promise<unknown> {
    return this.call("GET", `/api/v1/fulfillment/warehouses`, {}, undefined);
  }

  /** Create a gift card (POST /api/v1/gift-cards) */
  giftCardsCreate(input: { "amount": number; "customerId"?: string; "code"?: string; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/gift-cards`, query, all);
  }

  /** Get a gift card (GET /api/v1/gift-cards/{code}) */
  giftCardsGet(code: string): Promise<unknown> {
    return this.call("GET", `/api/v1/gift-cards/${encodeURIComponent(code)}`, {}, undefined);
  }

  /** List gift cards (GET /api/v1/gift-cards) */
  giftCardsList(input?: { "customerId"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["customerId"] = all["customerId"]; delete all["customerId"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/gift-cards`, query, undefined);
  }

  /** Void a gift card (POST /api/v1/gift-cards/{id}/void) */
  giftCardsVoid(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/gift-cards/${encodeURIComponent(id)}/void`, {}, undefined);
  }

  /** Create an adjust (POST /api/v1/inventory/adjust) */
  inventoryAdjust(input: { "outletId": string; "variantId": string; "qtyDelta": number; "reason"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/inventory/adjust`, query, all);
  }

  /** List batches (GET /api/v1/inventory/batches) */
  inventoryBatches(input?: { "all"?: unknown; "outletId"?: unknown; "variantId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["all"] = all["all"]; delete all["all"];
    query["outletId"] = all["outletId"]; delete all["outletId"];
    query["variantId"] = all["variantId"]; delete all["variantId"];
    return this.call("GET", `/api/v1/inventory/batches`, query, undefined);
  }

  /** Derived availability for COMPOSITE variants at an outlet. (GET /api/v1/inventory/composites) */
  inventoryComposites(input: { "outletId": unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("GET", `/api/v1/inventory/composites`, query, undefined);
  }

  /** Create a batch (POST /api/v1/inventory/batches) */
  inventoryCreateBatches(input: { "outletId": string; "variantId": string; "batchNo"?: string; "expiryDate"?: unknown; "qty": number; "cost"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/inventory/batches`, query, all);
  }

  /** List expiring (GET /api/v1/inventory/expiring) */
  inventoryExpiring(input?: { "days"?: unknown; "outletId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["days"] = all["days"]; delete all["days"];
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("GET", `/api/v1/inventory/expiring`, query, undefined);
  }

  /** List levels (GET /api/v1/inventory/levels) */
  inventoryLevels(input?: { "low"?: unknown; "outletId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["low"] = all["low"]; delete all["low"];
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("GET", `/api/v1/inventory/levels`, query, undefined);
  }

  /** List movements (GET /api/v1/inventory/movements) */
  inventoryMovements(input?: { "outletId"?: unknown; "variantId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["outletId"] = all["outletId"]; delete all["outletId"];
    query["variantId"] = all["variantId"]; delete all["variantId"];
    return this.call("GET", `/api/v1/inventory/movements`, query, undefined);
  }

  /** Set reorder (PUT /api/v1/inventory/reorder) */
  inventoryReorder(input: { "outletId": string; "variantId": string; "reorderPoint": number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/inventory/reorder`, query, all);
  }

  /** Create a transfer (POST /api/v1/inventory/transfer) */
  inventoryTransfer(input: { "fromOutletId": string; "toOutletId": string; "variantId": string; "qty": number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/inventory/transfer`, query, all);
  }

  /** Advance a kd (POST /api/v1/kds/{id}/advance) */
  kdsAdvance(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/kds/${encodeURIComponent(id)}/advance`, {}, undefined);
  }

  /** Back a kd (POST /api/v1/kds/{id}/back) */
  kdsBack(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/kds/${encodeURIComponent(id)}/back`, {}, undefined);
  }

  /** Nav-badge counts: active kitchen tickets + orders carrying a ready item (the serve board). (GET /api/v1/kds/counts) */
  kdsCounts(input?: { "outletId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("GET", `/api/v1/kds/counts`, query, undefined);
  }

  /** Advance an item (POST /api/v1/kds/items/{itemId}/advance) */
  kdsItemsAdvance(itemId: string): Promise<unknown> {
    return this.call("POST", `/api/v1/kds/items/${encodeURIComponent(itemId)}/advance`, {}, undefined);
  }

  /** Back an item (POST /api/v1/kds/items/{itemId}/back) */
  kdsItemsBack(itemId: string): Promise<unknown> {
    return this.call("POST", `/api/v1/kds/items/${encodeURIComponent(itemId)}/back`, {}, undefined);
  }

  /** List kds (GET /api/v1/kds) */
  kdsList(input?: { "outletId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("GET", `/api/v1/kds`, query, undefined);
  }

  /** Every ACTIVE ticket's outstanding items, grouped by table, oldest-first. (GET /api/v1/kds/ready) */
  kdsReady(input?: { "outletId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("GET", `/api/v1/kds/ready`, query, undefined);
  }

  /** Advance every currently-READY item across all of a table's active tickets to SERVED in one call, re-syncing each affected ticket's order state so a fully-served ticket drops off both boards. (POST /api/v1/kds/tables/{tableId}/serve) */
  kdsTablesServe(tableId: string, input?: { "outletId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("POST", `/api/v1/kds/tables/${encodeURIComponent(tableId)}/serve`, query, undefined);
  }

  /** Create a discount code (POST /api/v1/marketing/discount-codes) */
  marketingCreateDiscountCodes(input: { "code": string; "description"?: string; "type": "percent" | "fixed" | "shipping_percent" | "shipping_fixed"; "value": number; "currency"?: string; "scope"?: "cart" | "products" | "tags"; "productIds"?: unknown[]; "tagFilter"?: unknown[]; "minPurchaseAmount"?: number; "maxUsesTotal"?: number; "maxUsesPerCustomer"?: number; "startsAt"?: string; "expiresAt"?: string; "active"?: boolean; "public"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/marketing/discount-codes`, query, all);
  }

  /** Delete a discount code (DELETE /api/v1/marketing/discount-codes/{id}) */
  marketingDeleteDiscountCodes(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/marketing/discount-codes/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List discount codes (GET /api/v1/marketing/discount-codes) */
  marketingDiscountCodes(input?: { "active"?: unknown; "cursor"?: unknown; "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["active"] = all["active"]; delete all["active"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/marketing/discount-codes`, query, undefined);
  }

  /** Create a validate (POST /api/v1/marketing/discount-codes/validate) */
  marketingDiscountCodesValidate(input: { "code": string; "subtotal": number; "customerId"?: string; "shippingCost"?: number; "items"?: unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/marketing/discount-codes/validate`, query, all);
  }

  /** Get a discount code (GET /api/v1/marketing/discount-codes/{id}) */
  marketingGetDiscountCodes(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/marketing/discount-codes/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Member lookup — balance + recent ledger for one customer. (GET /api/v1/marketing/loyalty/members/{customerId}) */
  marketingLoyaltyMembers(customerId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/marketing/loyalty/members/${encodeURIComponent(customerId)}`, {}, undefined);
  }

  /** List program (GET /api/v1/marketing/loyalty/program) */
  marketingLoyaltyProgram(): Promise<unknown> {
    return this.call("GET", `/api/v1/marketing/loyalty/program`, {}, undefined);
  }

  /** Set program (PUT /api/v1/marketing/loyalty/program) */
  marketingSetLoyaltyProgram(input: { "enabled"?: boolean; "earnRatePoints": number; "redeemValueIdr": number; "marketingCampaignId"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/marketing/loyalty/program`, query, all);
  }

  /** Update a discount code (PATCH /api/v1/marketing/discount-codes/{id}) */
  marketingUpdateDiscountCodes(id: string, input?: { "code"?: unknown; "description"?: string; "type"?: "percent" | "fixed" | "shipping_percent" | "shipping_fixed"; "value"?: number; "currency"?: string; "scope"?: "cart" | "products" | "tags"; "productIds"?: unknown[]; "tagFilter"?: unknown[]; "minPurchaseAmount"?: number; "maxUsesTotal"?: number; "maxUsesPerCustomer"?: number; "startsAt"?: string; "expiresAt"?: string; "active"?: boolean; "public"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/marketing/discount-codes/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a modifier (POST /api/v1/modifiers) */
  modifiersCreate(input: { "name": string; "minSelect"?: number; "maxSelect"?: number; "sortOrder"?: number; "modifiers"?: unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/modifiers`, query, all);
  }

  /** Items a modifier (POST /api/v1/modifiers/{id}/items) */
  modifiersCreateItems(id: string, input: { "name": string; "price"?: number; "sortOrder"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/modifiers/${encodeURIComponent(id)}/items`, query, all);
  }

  /** Delete a modifier (DELETE /api/v1/modifiers/{id}) */
  modifiersDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/modifiers/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete an item (DELETE /api/v1/modifiers/{id}/items/{modId}) */
  modifiersDeleteItems(id: string, modId: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/modifiers/${encodeURIComponent(id)}/items/${encodeURIComponent(modId)}`, {}, undefined);
  }

  /** Get a modifier (GET /api/v1/modifiers/{id}) */
  modifiersGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/modifiers/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List modifiers (GET /api/v1/modifiers) */
  modifiersList(): Promise<unknown> {
    return this.call("GET", `/api/v1/modifiers`, {}, undefined);
  }

  /** Get a product (GET /api/v1/modifiers/product/{productId}) */
  modifiersProduct(productId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/modifiers/product/${encodeURIComponent(productId)}`, {}, undefined);
  }

  /** Replace a product (PUT /api/v1/modifiers/product/{productId}) */
  modifiersSetProduct(productId: string, input: { "groupIds": unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/modifiers/product/${encodeURIComponent(productId)}`, query, all);
  }

  /** Update a modifier (PATCH /api/v1/modifiers/{id}) */
  modifiersUpdate(id: string, input?: { "name"?: string; "minSelect"?: number; "maxSelect"?: number; "sortOrder"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/modifiers/${encodeURIComponent(id)}`, query, all);
  }

  /** Update an item (PATCH /api/v1/modifiers/{id}/items/{modId}) */
  modifiersUpdateItems(id: string, modId: string, input?: { "name"?: string; "price"?: number; "sortOrder"?: number; "isActive"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/modifiers/${encodeURIComponent(id)}/items/${encodeURIComponent(modId)}`, query, all);
  }

  /** Create a module (POST /api/v1/modules) */
  modulesCreate(input?: { "enabled"?: unknown; "module"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/modules`, query, all);
  }

  /** List modules (GET /api/v1/modules) */
  modulesList(): Promise<unknown> {
    return this.call("GET", `/api/v1/modules`, {}, undefined);
  }

  /** Create an outlet (POST /api/v1/outlets) */
  outletsCreate(input: { "name": string; "address"?: string; "phone"?: string; "timezone"?: string; "taxRateBps"?: number; "taxInclusive"?: boolean; "receiptHeader"?: string; "receiptFooter"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/outlets`, query, all);
  }

  /** Delete an outlet (DELETE /api/v1/outlets/{id}) */
  outletsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/outlets/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get an outlet (GET /api/v1/outlets/{id}) */
  outletsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/outlets/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List outlets (GET /api/v1/outlets) */
  outletsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/outlets`, {}, undefined);
  }

  /** Update an outlet (PATCH /api/v1/outlets/{id}) */
  outletsUpdate(id: string, input?: { "name"?: string; "address"?: string; "phone"?: string; "timezone"?: string; "taxRateBps"?: number; "taxInclusive"?: boolean; "receiptHeader"?: string; "receiptFooter"?: string; "isActive"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/outlets/${encodeURIComponent(id)}`, query, all);
  }

  /** List checkout sessions (GET /api/v1/payments/checkout-sessions) */
  paymentsCheckoutSessions(input?: { "limit"?: number; "status"?: string; "customerId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    query["status"] = all["status"]; delete all["status"];
    query["customerId"] = all["customerId"]; delete all["customerId"];
    return this.call("GET", `/api/v1/payments/checkout-sessions`, query, undefined);
  }

  /** Manual-adapter confirm — flips a pending_review session to completed. (POST /api/v1/payments/checkout-sessions/{id}/confirm) */
  paymentsCheckoutSessionsConfirm(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/payments/checkout-sessions/${encodeURIComponent(id)}/confirm`, {}, undefined);
  }

  /** Create a checkout session (POST /api/v1/payments/checkout-sessions) */
  paymentsCreateCheckoutSessions(input: { "amount": number; "currency"?: "IDR" | "USD"; "paymentMethods"?: unknown[]; "successUrl": string; "cancelUrl": string; "customerId"?: string; "expiresInMinutes"?: number; "metadata"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payments/checkout-sessions`, query, all);
  }

  /** Create a customer (POST /api/v1/payments/customers) */
  paymentsCreateCustomers(input: { "email": string; "name"?: string; "metadata"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payments/customers`, query, all);
  }

  /** Create a payout (POST /api/v1/payments/payouts) */
  paymentsCreatePayouts(input: { "amount": number; "currency"?: "IDR" | "USD"; "bankCode"?: string; "bankName"?: string; "bankAccountNumber"?: string; "bankAccountHolder"?: string; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payments/payouts`, query, all);
  }

  /** Create a plan (POST /api/v1/payments/plans) */
  paymentsCreatePlans(input: { "name": string; "amount": number; "currency"?: "IDR" | "USD"; "interval"?: string; "trialDays"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payments/plans`, query, all);
  }

  /** Add a new price (currency variant) to an existing plan. (POST /api/v1/payments/plans/{id}/prices) */
  paymentsCreatePlansPrices(id: string, input?: { "currency"?: unknown; "model"?: unknown; "taxMode"?: unknown; "unitAmount"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payments/plans/${encodeURIComponent(id)}/prices`, query, all);
  }

  /** Mint a dynamic-QRIS checkout session. (POST /api/v1/payments/qris) */
  paymentsCreateQris(input?: { "transactionId"?: string; "amount"?: number; "method"?: "qris" | "va"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payments/qris`, query, all);
  }

  /** Create a subscription (POST /api/v1/payments/subscriptions) */
  paymentsCreateSubscriptions(input: { "customerId": string; "planId": string; "priceId"?: string; "trialEnd"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payments/subscriptions`, query, all);
  }

  /** List customers (GET /api/v1/payments/customers) */
  paymentsCustomers(input?: { "limit"?: number; "cursor"?: string; "email"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["email"] = all["email"]; delete all["email"];
    return this.call("GET", `/api/v1/payments/customers`, query, undefined);
  }

  /** Delete a plan (DELETE /api/v1/payments/plans/{id}) */
  paymentsDeletePlans(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/payments/plans/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete a subscription (DELETE /api/v1/payments/subscriptions/{id}) */
  paymentsDeleteSubscriptions(id: string, input?: { "immediate"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["immediate"] = all["immediate"]; delete all["immediate"];
    return this.call("DELETE", `/api/v1/payments/subscriptions/${encodeURIComponent(id)}`, query, undefined);
  }

  /** Get a checkout session (GET /api/v1/payments/checkout-sessions/{id}) */
  paymentsGetCheckoutSessions(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/checkout-sessions/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a customer (GET /api/v1/payments/customers/{id}) */
  paymentsGetCustomers(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/customers/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get an invoice (GET /api/v1/payments/invoices/{id}) */
  paymentsGetInvoices(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/invoices/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get an entry (GET /api/v1/payments/ledger/entries/{id}) */
  paymentsGetLedgerEntries(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/ledger/entries/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a payout (GET /api/v1/payments/payouts/{id}) */
  paymentsGetPayouts(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/payouts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a plan (GET /api/v1/payments/plans/{id}) */
  paymentsGetPlans(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/plans/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a receipt (GET /api/v1/payments/receipts/{id}) */
  paymentsGetReceipts(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/receipts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a subscription (GET /api/v1/payments/subscriptions/{id}) */
  paymentsGetSubscriptions(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/subscriptions/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List invoices (GET /api/v1/payments/invoices) */
  paymentsInvoices(input?: { "limit"?: number; "cursor"?: string; "status"?: string; "customerId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["status"] = all["status"]; delete all["status"];
    query["customerId"] = all["customerId"]; delete all["customerId"];
    return this.call("GET", `/api/v1/payments/invoices`, query, undefined);
  }

  /** CSV export — up to 10k rows via paginated SDK fetch. (GET /api/v1/payments/invoices/export.csv) */
  paymentsInvoicesExportCsv(): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/invoices/export.csv`, {}, undefined);
  }

  /** List html (GET /api/v1/payments/invoices/{id}/html) */
  paymentsInvoicesHtml(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/invoices/${encodeURIComponent(id)}/html`, {}, undefined);
  }

  /** PDF / HTML preview — streamed straight from Plugipay's hosted endpoints. (GET /api/v1/payments/invoices/{id}/pdf) */
  paymentsInvoicesPdf(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/invoices/${encodeURIComponent(id)}/pdf`, {}, undefined);
  }

  /** List balance (GET /api/v1/payments/ledger/balance) */
  paymentsLedgerBalance(): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/ledger/balance`, {}, undefined);
  }

  /** List entries (GET /api/v1/payments/ledger/entries) */
  paymentsLedgerEntries(input?: { "code"?: unknown; "cursor"?: unknown; "limit"?: unknown; "sourceId"?: unknown; "sourceType"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["code"] = all["code"]; delete all["code"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["sourceId"] = all["sourceId"]; delete all["sourceId"];
    query["sourceType"] = all["sourceType"]; delete all["sourceType"];
    return this.call("GET", `/api/v1/payments/ledger/entries`, query, undefined);
  }

  /** CSV export — up to 10k rows. (GET /api/v1/payments/ledger/entries.csv) */
  paymentsLedgerEntriesCsv(): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/ledger/entries.csv`, {}, undefined);
  }

  /** A workspace payments dashboard via the merchant client: available balance, recent QRIS checkout sessions, and recent payouts. (GET /api/v1/payments/overview) */
  paymentsOverview(): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/overview`, {}, undefined);
  }

  /** List payouts (GET /api/v1/payments/payouts) */
  paymentsPayouts(input?: { "cursor"?: unknown; "limit"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/payments/payouts`, query, undefined);
  }

  /** List balance (GET /api/v1/payments/payouts/balance) */
  paymentsPayoutsBalance(): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/payouts/balance`, {}, undefined);
  }

  /** List bank account (GET /api/v1/payments/payouts/bank-account) */
  paymentsPayoutsBankAccount(): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/payouts/bank-account`, {}, undefined);
  }

  /** Cancel a payout (POST /api/v1/payments/payouts/{id}/cancel) */
  paymentsPayoutsCancel(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/payments/payouts/${encodeURIComponent(id)}/cancel`, {}, undefined);
  }

  /** Mark failed a payout (POST /api/v1/payments/payouts/{id}/mark-failed) */
  paymentsPayoutsMarkFailed(id: string, input: { "failureReason": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payments/payouts/${encodeURIComponent(id)}/mark-failed`, query, all);
  }

  /** Mark in transit a payout (POST /api/v1/payments/payouts/{id}/mark-in-transit) */
  paymentsPayoutsMarkInTransit(id: string, input?: { "reference"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payments/payouts/${encodeURIComponent(id)}/mark-in-transit`, query, all);
  }

  /** Mark paid a payout (POST /api/v1/payments/payouts/{id}/mark-paid) */
  paymentsPayoutsMarkPaid(id: string, input?: { "reference"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payments/payouts/${encodeURIComponent(id)}/mark-paid`, query, all);
  }

  /** List plans (GET /api/v1/payments/plans) */
  paymentsPlans(input?: { "limit"?: number; "cursor"?: string; "active"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["active"] = all["active"]; delete all["active"];
    return this.call("GET", `/api/v1/payments/plans`, query, undefined);
  }

  /** Template preview returns raw HTML (not envelope JSON) — route through the raw-passthrough helper so the catch-all below doesn't JSON-parse it. (POST /api/v1/payments/plugipay-settings/templates/preview) */
  paymentsPlugipaySettingsTemplatesPreview(input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payments/plugipay-settings/templates/preview`, query, all);
  }

  /** Poll the session status so the sell screen can wait for the customer's scan to confirm. (GET /api/v1/payments/qris/{sessionId}) */
  paymentsQris(sessionId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/qris/${encodeURIComponent(sessionId)}`, {}, undefined);
  }

  /** List receipts (GET /api/v1/payments/receipts) */
  paymentsReceipts(input?: { "cursor"?: unknown; "customerId"?: unknown; "limit"?: unknown; "sourceType"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["customerId"] = all["customerId"]; delete all["customerId"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["sourceType"] = all["sourceType"]; delete all["sourceType"];
    return this.call("GET", `/api/v1/payments/receipts`, query, undefined);
  }

  /** Email a receipt to the customer. `to` optional — falls back to the receipt's customer email on the Plugipay side. (POST /api/v1/payments/receipts/{id}/email) */
  paymentsReceiptsEmail(id: string, input?: { "to"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/payments/receipts/${encodeURIComponent(id)}/email`, query, all);
  }

  /** List escpos (GET /api/v1/payments/receipts/{id}/escpos) */
  paymentsReceiptsEscpos(id: string, input?: { "width"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["width"] = all["width"]; delete all["width"];
    return this.call("GET", `/api/v1/payments/receipts/${encodeURIComponent(id)}/escpos`, query, undefined);
  }

  /** List html (GET /api/v1/payments/receipts/{id}/html) */
  paymentsReceiptsHtml(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/receipts/${encodeURIComponent(id)}/html`, {}, undefined);
  }

  /** Binary passthroughs — PDF, HTML, ESC/POS thermal. (GET /api/v1/payments/receipts/{id}/pdf) */
  paymentsReceiptsPdf(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/receipts/${encodeURIComponent(id)}/pdf`, {}, undefined);
  }

  /** List cash flow (GET /api/v1/payments/reports/cash-flow) */
  paymentsReportsCashFlow(): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/reports/cash-flow`, {}, undefined);
  }

  /** List pnl (GET /api/v1/payments/reports/pnl) */
  paymentsReportsPnl(): Promise<unknown> {
    return this.call("GET", `/api/v1/payments/reports/pnl`, {}, undefined);
  }

  /** List subscriptions (GET /api/v1/payments/subscriptions) */
  paymentsSubscriptions(input?: { "limit"?: number; "status"?: string; "customerId"?: string; "planId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    query["status"] = all["status"]; delete all["status"];
    query["customerId"] = all["customerId"]; delete all["customerId"];
    query["planId"] = all["planId"]; delete all["planId"];
    return this.call("GET", `/api/v1/payments/subscriptions`, query, undefined);
  }

  /** Update a customer (PATCH /api/v1/payments/customers/{id}) */
  paymentsUpdateCustomers(id: string, input?: { "email"?: string; "name"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/payments/customers/${encodeURIComponent(id)}`, query, all);
  }

  /** Update bank account (PATCH /api/v1/payments/payouts/bank-account) */
  paymentsUpdatePayoutsBankAccount(input: { "bankCode"?: string; "bankName": string; "bankAccountNumber": string; "bankAccountHolder": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/payments/payouts/bank-account`, query, all);
  }

  /** Update a plan (PATCH /api/v1/payments/plans/{id}) */
  paymentsUpdatePlans(id: string, input?: { "name"?: string; "description"?: string; "active"?: boolean; "metadata"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/payments/plans/${encodeURIComponent(id)}`, query, all);
  }

  /** Archive/unarchive an individual price. (PATCH /api/v1/payments/plans/prices/{priceId}) */
  paymentsUpdatePlansPrices(priceId: string, input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/payments/plans/prices/${encodeURIComponent(priceId)}`, query, all);
  }

  /** Update a subscription (PATCH /api/v1/payments/subscriptions/{id}) */
  paymentsUpdateSubscriptions(id: string, input?: { "status"?: "active" | "paused"; "action"?: "pause" | "resume"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/payments/subscriptions/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a bulk category (POST /api/v1/products/bulk-category) */
  productsBulkCategory(input: { "productIds": unknown[]; "categoryId": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/products/bulk-category`, query, all);
  }

  /** Create a product (POST /api/v1/products) */
  productsCreate(input: { "name": string; "description"?: string; "categoryId"?: string; "kind"?: "GOODS" | "SERVICE"; "trackStock"?: boolean; "requiresBatch"?: boolean; "imageUrl"?: string; "isActive"?: boolean; "variants": unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/products`, query, all);
  }

  /** Variants a product (POST /api/v1/products/{id}/variants) */
  productsCreateVariants(id: string, input: { "name"?: string; "sku"?: string; "barcode"?: string; "price": number; "cost"?: number; "sortOrder"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/products/${encodeURIComponent(id)}/variants`, query, all);
  }

  /** Delete a product (DELETE /api/v1/products/{id}) */
  productsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/products/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete a variant (DELETE /api/v1/products/{id}/variants/{vid}) */
  productsDeleteVariants(id: string, vid: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/products/${encodeURIComponent(id)}/variants/${encodeURIComponent(vid)}`, {}, undefined);
  }

  /** Get a product (GET /api/v1/products/{id}) */
  productsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/products/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List products (GET /api/v1/products) */
  productsList(input?: { "active"?: unknown; "categoryId"?: unknown; "q"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["active"] = all["active"]; delete all["active"];
    query["categoryId"] = all["categoryId"]; delete all["categoryId"];
    query["q"] = all["q"]; delete all["q"];
    return this.call("GET", `/api/v1/products`, query, undefined);
  }

  /** Sell-screen lookup: exact barcode match first, else fuzzy name/sku. (GET /api/v1/products/lookup) */
  productsLookup(input?: { "barcode"?: unknown; "q"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["barcode"] = all["barcode"]; delete all["barcode"];
    query["q"] = all["q"]; delete all["q"];
    return this.call("GET", `/api/v1/products/lookup`, query, undefined);
  }

  /** Replace-all the components of a variant + set its isComposite flag. (PUT /api/v1/products/{id}/variants/{vid}/recipe) */
  productsSetVariantsRecipe(id: string, vid: string, input: { "isComposite": boolean; "components"?: unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/products/${encodeURIComponent(id)}/variants/${encodeURIComponent(vid)}/recipe`, query, all);
  }

  /** Update a product (PATCH /api/v1/products/{id}) */
  productsUpdate(id: string, input?: { "name"?: string; "description"?: string; "categoryId"?: string; "kind"?: "GOODS" | "SERVICE"; "trackStock"?: boolean; "requiresBatch"?: boolean; "imageUrl"?: string; "isActive"?: boolean; "variants"?: unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/products/${encodeURIComponent(id)}`, query, all);
  }

  /** Update a variant (PATCH /api/v1/products/{id}/variants/{vid}) */
  productsUpdateVariants(id: string, vid: string, input?: { "name"?: string; "sku"?: string; "barcode"?: string; "price"?: number; "cost"?: number; "sortOrder"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/products/${encodeURIComponent(id)}/variants/${encodeURIComponent(vid)}`, query, all);
  }

  /** List recipe (GET /api/v1/products/{id}/variants/{vid}/recipe) */
  productsVariantsRecipe(id: string, vid: string): Promise<unknown> {
    return this.call("GET", `/api/v1/products/${encodeURIComponent(id)}/variants/${encodeURIComponent(vid)}/recipe`, {}, undefined);
  }

  /** Cancel a purchase order (POST /api/v1/purchase-orders/{id}/cancel) */
  purchaseOrdersCancel(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/purchase-orders/${encodeURIComponent(id)}/cancel`, {}, undefined);
  }

  /** Create a purchase order (POST /api/v1/purchase-orders) */
  purchaseOrdersCreate(input: { "outletId": string; "supplierId"?: string; "items": unknown[]; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/purchase-orders`, query, all);
  }

  /** Get a purchase order (GET /api/v1/purchase-orders/{id}) */
  purchaseOrdersGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/purchase-orders/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List purchase orders (GET /api/v1/purchase-orders) */
  purchaseOrdersList(input?: { "outletId"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["outletId"] = all["outletId"]; delete all["outletId"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/purchase-orders`, query, undefined);
  }

  /** Order a purchase order (POST /api/v1/purchase-orders/{id}/order) */
  purchaseOrdersOrder(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/purchase-orders/${encodeURIComponent(id)}/order`, {}, undefined);
  }

  /** Receive a purchase order (POST /api/v1/purchase-orders/{id}/receive) */
  purchaseOrdersReceive(id: string, input: { "items": unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/purchase-orders/${encodeURIComponent(id)}/receive`, query, all);
  }

  /** Update a purchase order (PATCH /api/v1/purchase-orders/{id}) */
  purchaseOrdersUpdate(id: string, input: { "supplierId"?: string; "items": unknown[]; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/purchase-orders/${encodeURIComponent(id)}`, query, all);
  }

  /** List low stock (GET /api/v1/reports/low-stock) */
  reportsLowStock(input?: { "outletId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("GET", `/api/v1/reports/low-stock`, query, undefined);
  }

  /** List sales by day (GET /api/v1/reports/sales-by-day) */
  reportsSalesByDay(input?: { "days"?: unknown; "from"?: unknown; "to"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["days"] = all["days"]; delete all["days"];
    query["from"] = all["from"]; delete all["from"];
    query["to"] = all["to"]; delete all["to"];
    return this.call("GET", `/api/v1/reports/sales-by-day`, query, undefined);
  }

  /** List summary (GET /api/v1/reports/summary) */
  reportsSummary(): Promise<unknown> {
    return this.call("GET", `/api/v1/reports/summary`, {}, undefined);
  }

  /** List top products (GET /api/v1/reports/top-products) */
  reportsTopProducts(input?: { "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/reports/top-products`, query, undefined);
  }

  /** Create a sale (POST /api/v1/sales) */
  salesCreate(input: { "outletId": string; "shiftId"?: string; "customerId"?: string; "tableId"?: string; "orderType"?: "DINE_IN" | "TAKEAWAY" | "DELIVERY"; "items": unknown[]; "orderDiscount"?: number; "deliveryFee"?: number; "deliveryDraft"?: unknown; "payments"?: unknown[]; "status"?: "COMPLETED" | "PARKED"; "note"?: string; "discountCode"?: string; "redeemPoints"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/sales`, query, all);
  }

  /** Abandon a PARKED sale (e.g. an unpaid dynamic-QRIS sale). (POST /api/v1/sales/{id}/discard) */
  salesDiscard(id: string, input?: { "reason"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/sales/${encodeURIComponent(id)}/discard`, query, all);
  }

  /** Get a sale (GET /api/v1/sales/{id}) */
  salesGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/sales/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Edit an open bill (PARKED sale): replace its line items + recompute totals, optionally re-seat or attach a customer. (PATCH /api/v1/sales/{id}/items) */
  salesItems(id: string, input: { "items": unknown[]; "orderDiscount"?: number; "note"?: string; "tableId"?: string; "orderType"?: "DINE_IN" | "TAKEAWAY" | "DELIVERY"; "customerId"?: string; "deliveryDraft"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/sales/${encodeURIComponent(id)}/items`, query, all);
  }

  /** List sales (GET /api/v1/sales) */
  salesList(input?: { "orderType"?: unknown; "outletId"?: unknown; "shiftId"?: unknown; "status"?: unknown; "tableId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["orderType"] = all["orderType"]; delete all["orderType"];
    query["outletId"] = all["outletId"]; delete all["outletId"];
    query["shiftId"] = all["shiftId"]; delete all["shiftId"];
    query["status"] = all["status"]; delete all["status"];
    query["tableId"] = all["tableId"]; delete all["tableId"];
    return this.call("GET", `/api/v1/sales`, query, undefined);
  }

  /** Record ONE tender against an open bill (PARKED) for split-bill checkout. (POST /api/v1/sales/{id}/payments) */
  salesPayments(id: string, input: { "method": "CASH" | "QRIS" | "VA" | "CARD" | "TRANSFER" | "GIFT_CARD" | "OTHER"; "amount": number; "tendered"?: number; "reference"?: string; "plugipayRef"?: string; "status"?: "PENDING" | "PAID" | "FAILED"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/sales/${encodeURIComponent(id)}/payments`, query, all);
  }

  /** Refund a sale (POST /api/v1/sales/{id}/refund) */
  salesRefund(id: string, input?: { "lines"?: unknown[]; "amount"?: number; "restock"?: boolean; "refundToStoreCredit"?: boolean; "reason"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/sales/${encodeURIComponent(id)}/refund`, query, all);
  }

  /** Charge an open bill (PARKED → COMPLETED) with manual tenders, reusing the shared completion side-effects (stock + loyalty + event). (POST /api/v1/sales/{id}/settle) */
  salesSettle(id: string, input: { "payments": unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/sales/${encodeURIComponent(id)}/settle`, query, all);
  }

  /** Void a sale (POST /api/v1/sales/{id}/void) */
  salesVoid(id: string, input?: { "reason"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/sales/${encodeURIComponent(id)}/void`, query, all);
  }

  /** List settings (GET /api/v1/settings) */
  settingsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/settings`, {}, undefined);
  }

  /** Set settings (PUT /api/v1/settings) */
  settingsSet(input?: { "businessName"?: string; "businessType"?: "RETAIL" | "FNB" | "PHARMACY" | "GENERAL"; "currency"?: string; "transferBankName"?: string; "transferBankAccountNumber"?: string; "transferBankAccountHolder"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/settings`, query, all);
  }

  /** Close a shift (POST /api/v1/shifts/{id}/close) */
  shiftsClose(id: string, input: { "countedCash": number; "notes"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/shifts/${encodeURIComponent(id)}/close`, query, all);
  }

  /** List current (GET /api/v1/shifts/current) */
  shiftsCurrent(input: { "outletId": unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("GET", `/api/v1/shifts/current`, query, undefined);
  }

  /** Get a shift (GET /api/v1/shifts/{id}) */
  shiftsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/shifts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List shifts (GET /api/v1/shifts) */
  shiftsList(input?: { "outletId"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["outletId"] = all["outletId"]; delete all["outletId"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/shifts`, query, undefined);
  }

  /** Create an open (POST /api/v1/shifts/open) */
  shiftsOpen(input: { "outletId": string; "openingFloat": number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/shifts/open`, query, all);
  }

  /** Create a supplier (POST /api/v1/suppliers) */
  suppliersCreate(input: { "name": string; "contact"?: string; "phone"?: string; "email"?: string; "address"?: string; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/suppliers`, query, all);
  }

  /** Delete a supplier (DELETE /api/v1/suppliers/{id}) */
  suppliersDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/suppliers/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a supplier (GET /api/v1/suppliers/{id}) */
  suppliersGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/suppliers/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List suppliers (GET /api/v1/suppliers) */
  suppliersList(input?: { "q"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["q"] = all["q"]; delete all["q"];
    return this.call("GET", `/api/v1/suppliers`, query, undefined);
  }

  /** Update a supplier (PATCH /api/v1/suppliers/{id}) */
  suppliersUpdate(id: string, input?: { "name"?: string; "contact"?: string; "phone"?: string; "email"?: string; "address"?: string; "note"?: string; "isActive"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/suppliers/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a table (POST /api/v1/tables) */
  tablesCreate(input: { "outletId": string; "floorId"?: string; "label": string; "zone"?: string; "seats"?: number; "sortOrder"?: number; "posX"?: number; "posY"?: number; "shape"?: "SQUARE" | "ROUND" | "RECT"; "width"?: number; "height"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/tables`, query, all);
  }

  /** Delete a table (DELETE /api/v1/tables/{id}) */
  tablesDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/tables/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** The live floor: every active table with its current open bill (the most-recent PARKED transaction seated at it, if any). `openBill` is null for an available table. (GET /api/v1/tables/floor) */
  tablesFloor(input: { "floorId"?: unknown; "outletId": unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["floorId"] = all["floorId"]; delete all["floorId"];
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("GET", `/api/v1/tables/floor`, query, undefined);
  }

  /** Bulk-save the floor map. (PUT /api/v1/tables/layout) */
  tablesLayout(input: { "outletId": string; "floorId"?: string; "tables": unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/tables/layout`, query, all);
  }

  /** List tables (GET /api/v1/tables) */
  tablesList(input: { "floorId"?: unknown; "includeInactive"?: unknown; "outletId": unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["floorId"] = all["floorId"]; delete all["floorId"];
    query["includeInactive"] = all["includeInactive"]; delete all["includeInactive"];
    query["outletId"] = all["outletId"]; delete all["outletId"];
    return this.call("GET", `/api/v1/tables`, query, undefined);
  }

  /** Update a table (PATCH /api/v1/tables/{id}) */
  tablesUpdate(id: string, input?: { "label"?: string; "floorId"?: string; "zone"?: string; "seats"?: number; "sortOrder"?: number; "isActive"?: boolean; "posX"?: number; "posY"?: number; "shape"?: "SQUARE" | "ROUND" | "RECT"; "width"?: number; "height"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/tables/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a sign (POST /api/v1/uploads/sign) */
  uploadsSign(input: { "contentType": string; "ext"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/uploads/sign`, query, all);
  }

  /** Create a webhook subscription (POST /api/v1/webhook-subscriptions) */
  webhookSubscriptionsCreate(input: { "url": string; "events"?: unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/webhook-subscriptions`, query, all);
  }

  /** Delete a webhook subscription (DELETE /api/v1/webhook-subscriptions/{id}) */
  webhookSubscriptionsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/webhook-subscriptions/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List webhook subscriptions (GET /api/v1/webhook-subscriptions) */
  webhookSubscriptionsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/webhook-subscriptions`, {}, undefined);
  }

  /** Update a webhook subscription (PATCH /api/v1/webhook-subscriptions/{id}) */
  webhookSubscriptionsUpdate(id: string, input: { "active": boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/webhook-subscriptions/${encodeURIComponent(id)}`, query, all);
  }

  /** @deprecated The old name of `accountGetBlogPosts` (GET /api/v1/account/blog/posts/{id}). */
  accountBlogPosts2(...args: Parameters<GeneratedApi["accountGetBlogPosts"]>): Promise<unknown> {
    return this.accountGetBlogPosts(...args);
  }

  /** @deprecated The old name of `deliveryGetShipments` (GET /api/v1/delivery/shipments/{id}). */
  deliveryShipments2(...args: Parameters<GeneratedApi["deliveryGetShipments"]>): Promise<unknown> {
    return this.deliveryGetShipments(...args);
  }

  /** @deprecated The old name of `fulfillmentGetDeliveries` (GET /api/v1/fulfillment/deliveries/{id}). */
  fulfillmentDeliveries2(...args: Parameters<GeneratedApi["fulfillmentGetDeliveries"]>): Promise<unknown> {
    return this.fulfillmentGetDeliveries(...args);
  }

  /** @deprecated The old name of `fulfillmentGetShipments` (GET /api/v1/fulfillment/shipments/{id}). */
  fulfillmentShipments2(...args: Parameters<GeneratedApi["fulfillmentGetShipments"]>): Promise<unknown> {
    return this.fulfillmentGetShipments(...args);
  }

  /** @deprecated The old name of `marketingGetDiscountCodes` (GET /api/v1/marketing/discount-codes/{id}). */
  marketingDiscountCodes2(...args: Parameters<GeneratedApi["marketingGetDiscountCodes"]>): Promise<unknown> {
    return this.marketingGetDiscountCodes(...args);
  }

  /** @deprecated The old name of `paymentsGetCheckoutSessions` (GET /api/v1/payments/checkout-sessions/{id}). */
  paymentsCheckoutSessions2(...args: Parameters<GeneratedApi["paymentsGetCheckoutSessions"]>): Promise<unknown> {
    return this.paymentsGetCheckoutSessions(...args);
  }

  /** @deprecated The old name of `paymentsGetCustomers` (GET /api/v1/payments/customers/{id}). */
  paymentsCustomers2(...args: Parameters<GeneratedApi["paymentsGetCustomers"]>): Promise<unknown> {
    return this.paymentsGetCustomers(...args);
  }

  /** @deprecated The old name of `paymentsGetInvoices` (GET /api/v1/payments/invoices/{id}). */
  paymentsInvoices2(...args: Parameters<GeneratedApi["paymentsGetInvoices"]>): Promise<unknown> {
    return this.paymentsGetInvoices(...args);
  }

  /** @deprecated The old name of `paymentsGetLedgerEntries` (GET /api/v1/payments/ledger/entries/{id}). */
  paymentsLedgerEntries2(...args: Parameters<GeneratedApi["paymentsGetLedgerEntries"]>): Promise<unknown> {
    return this.paymentsGetLedgerEntries(...args);
  }

  /** @deprecated The old name of `paymentsGetPayouts` (GET /api/v1/payments/payouts/{id}). */
  paymentsPayouts2(...args: Parameters<GeneratedApi["paymentsGetPayouts"]>): Promise<unknown> {
    return this.paymentsGetPayouts(...args);
  }

  /** @deprecated The old name of `paymentsGetPlans` (GET /api/v1/payments/plans/{id}). */
  paymentsPlans2(...args: Parameters<GeneratedApi["paymentsGetPlans"]>): Promise<unknown> {
    return this.paymentsGetPlans(...args);
  }

  /** @deprecated The old name of `paymentsGetReceipts` (GET /api/v1/payments/receipts/{id}). */
  paymentsReceipts2(...args: Parameters<GeneratedApi["paymentsGetReceipts"]>): Promise<unknown> {
    return this.paymentsGetReceipts(...args);
  }

  /** @deprecated The old name of `paymentsGetSubscriptions` (GET /api/v1/payments/subscriptions/{id}). */
  paymentsSubscriptions2(...args: Parameters<GeneratedApi["paymentsGetSubscriptions"]>): Promise<unknown> {
    return this.paymentsGetSubscriptions(...args);
  }
}
