// Generated by apigen docs from backend/openapi.json — do not edit by hand.
import type { DocMeta } from './markdown';

export const REFERENCE_NAV: DocMeta[] = [
  {
    "slug": "api/reference",
    "title": "All routes",
    "group": "API reference (every route)",
    "href": "/docs/api/reference"
  },
  {
    "slug": "api/reference/account",
    "title": "Account",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/account"
  },
  {
    "slug": "api/reference/api-keys",
    "title": "Api keys",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/api-keys"
  },
  {
    "slug": "api/reference/audit-log",
    "title": "Audit log",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/audit-log"
  },
  {
    "slug": "api/reference/billing",
    "title": "Billing",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/billing"
  },
  {
    "slug": "api/reference/categories",
    "title": "Categories",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/categories"
  },
  {
    "slug": "api/reference/customers",
    "title": "Customers",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/customers"
  },
  {
    "slug": "api/reference/delivery",
    "title": "Delivery",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/delivery"
  },
  {
    "slug": "api/reference/events",
    "title": "Events",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/events"
  },
  {
    "slug": "api/reference/floors",
    "title": "Floors",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/floors"
  },
  {
    "slug": "api/reference/fulfillment",
    "title": "Fulfillment",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/fulfillment"
  },
  {
    "slug": "api/reference/gift-cards",
    "title": "Gift cards",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/gift-cards"
  },
  {
    "slug": "api/reference/inventory",
    "title": "Inventory",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/inventory"
  },
  {
    "slug": "api/reference/kds",
    "title": "Kds",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/kds"
  },
  {
    "slug": "api/reference/marketing",
    "title": "Marketing",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/marketing"
  },
  {
    "slug": "api/reference/modifiers",
    "title": "Modifiers",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/modifiers"
  },
  {
    "slug": "api/reference/modules",
    "title": "Modules",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/modules"
  },
  {
    "slug": "api/reference/outlets",
    "title": "Outlets",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/outlets"
  },
  {
    "slug": "api/reference/payments",
    "title": "Payments",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/payments"
  },
  {
    "slug": "api/reference/products",
    "title": "Products",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/products"
  },
  {
    "slug": "api/reference/purchase-orders",
    "title": "Purchase orders",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/purchase-orders"
  },
  {
    "slug": "api/reference/reports",
    "title": "Reports",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/reports"
  },
  {
    "slug": "api/reference/sales",
    "title": "Sales",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/sales"
  },
  {
    "slug": "api/reference/settings",
    "title": "Settings",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/settings"
  },
  {
    "slug": "api/reference/shifts",
    "title": "Shifts",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/shifts"
  },
  {
    "slug": "api/reference/suppliers",
    "title": "Suppliers",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/suppliers"
  },
  {
    "slug": "api/reference/tables",
    "title": "Tables",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/tables"
  },
  {
    "slug": "api/reference/uploads",
    "title": "Uploads",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/uploads"
  },
  {
    "slug": "api/reference/webhook-subscriptions",
    "title": "Webhook subscriptions",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/webhook-subscriptions"
  }
];
