// AUTO-GENERATED by scripts/gen-version.mjs — DO NOT EDIT BY HAND.
// Regenerated on every build/dev via the prebuild/predev npm hooks.
// Safe to commit (placeholder values); the real values come from git at build.
export const APP_VERSION = "ca3c77b-dirty";
export const BUILD_SHA = "ca3c77b";
export const BUILD_DATE = "2026-08-11T12:29:39.227Z";
