// AUTO-GENERATED by scripts/gen-version.mjs — DO NOT EDIT BY HAND.
// Regenerated on every build/dev via the prebuild/predev npm hooks.
// Safe to commit (placeholder values); the real values come from git at build.
export const APP_VERSION = "f2f85e0-dirty";
export const BUILD_SHA = "f2f85e0";
export const BUILD_DATE = "2026-08-12T11:54:09.073Z";
