// AUTO-GENERATED by scripts/gen-version.mjs — DO NOT EDIT BY HAND.
// Regenerated on every build/dev via the prebuild/predev npm hooks.
// Safe to commit (placeholder values); the real values come from git at build.
export const APP_VERSION = "d3305ac-dirty";
export const BUILD_SHA = "d3305ac";
export const BUILD_DATE = "2026-08-12T00:16:23.661Z";
